import { readFileSync, writeFileSync } from "node:fs";
import fm from "front-matter";
import { computeDocRoute, DOCS_DIR, walkMd } from "./doc-routes";

const SECTION_ORDER = ["开始使用", "安装与排错", "规则开发", "原理与实现"];

interface Frontmatter {
	title: string;
	section: string;
	icon: string;
	order?: number;
	slug?: string;
	authors?: string[];
}

interface PageEntry {
	route: string;
	title: string;
	icon: string;
	order: number;
}

const files = walkMd(DOCS_DIR);
const sectionMap = new Map<string, PageEntry[]>();

for (const file of files) {
	const raw = readFileSync(file, "utf-8");
	const { attributes } = fm(raw);
	const a = attributes as Frontmatter;
	if (!a.title || !a.section || !a.icon) continue;

	const route = computeDocRoute(file);

	if (!sectionMap.has(a.section)) {
		sectionMap.set(a.section, []);
	}
	sectionMap.get(a.section)?.push({
		route,
		title: a.title,
		icon: a.icon,
		order: a.order ?? 999,
	});
}

for (const pages of sectionMap.values()) {
	pages.sort((x, y) => x.order - y.order);
}

const orderedNames: string[] = [];
for (const name of SECTION_ORDER) {
	if (sectionMap.has(name)) {
		orderedNames.push(name);
	}
}
for (const name of [...sectionMap.keys()].sort()) {
	if (!orderedNames.includes(name)) {
		orderedNames.push(name);
	}
}

const sections = orderedNames.map((title) => ({
	title,
	pages: (sectionMap.get(title) ?? []).map(({ route, title: t, icon }) => ({
		route,
		title: t,
		icon,
	})),
}));

writeFileSync("public/doc-nav.json", JSON.stringify(sections, null, "\t"));

const tsContent =
	"// Auto-generated by generate-doc-nav.ts — do not edit\n" +
	'import type { DocSection } from "./docs-nav";\n' +
	"\n" +
	"export const DOC_NAV_DATA: DocSection[] = " +
	JSON.stringify(sections, null, "\t") +
	";\n";
writeFileSync("src/app/features/docs/doc-nav-data.ts", tsContent);

console.log("doc-nav.json:", sections.length, "sections");
